# Generated by Django 4.2.2 on 2023-06-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VideoHosting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="video",
            name="views_count",
            field=models.IntegerField(default=0),
        ),
    ]
