# Generated by Django 4.2.2 on 2023-06-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VideoHosting", "0006_video_preview_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={"ordering": ["-id"]},
        ),
    ]
