# Generated by Django 4.2.2 on 2023-06-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VideoHosting", "0007_alter_history_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="cloud_name",
            field=models.TextField(max_length=300, null=True),
        ),
    ]
