# Generated by Django 4.2.2 on 2023-06-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("VideoHosting", "0008_video_cloud_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="VideoHosting.video",
            ),
        ),
    ]
